# Generated by Django 5.1.4 on 2025-01-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FruitApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='poster',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
